version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - /home/${DOCKER_USER}/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
